name: Build

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: |
          pnpm lint --max-warnings=0
          pnpm format:check

      # - name: Test
      #   run: pnpm test:ci

      - name: Build
        run: pnpm build
